spring:
  application:
    name: jooq-project
  datasource:
    url: jdbc:mysql://localhost:3306/sakila?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root


logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: debug
